### ISSUE TITLE
No element found for selector

### ISSUE THREAD

**Issue by ghassenelkamel** [joaosilvalopes/linkedin-easy-apply-bot#64]
#### Issue Description

**Error:** No element found for selector: `input[id*="jobs-search-box-keyword-id"]`

#### Problem

When running the `npm run start` command, the script encounters an error while interacting with the LinkedIn website. It fails to find an input element with the selector `input[id*="jobs-search-box-keyword-id"]`. 

#### Steps to Reproduce

1. Execute the command `npm run start`.
2. Observe the error message mentioned above.

#### Expected Behavior

The script should be able to locate the input element with the selector `input[id*="jobs-search-box-keyword-id"]` on the LinkedIn page.

#### Actual Behavior

The script throws an error indicating that it cannot find the specified input element.

#### Requested Help

I'm seeking assistance in resolving this issue. Can someone help me understand why the script is unable to find the expected input element and provide guidance on how to fix it?

Please let me know if any additional information is required.

**Comment by IggsGrey** [comment]
Hi @MrJamieMcC , I encountered this issue a few days ago myself.

The problem is that the page is being rendered too slow and the selector is being searched for too early, what you can do (temporarily) while we wait for @joaosilvalopes to respond is to add a delay before the selector.

fetchJobLinksUser.ts:13
```js
await new Promise((resolve) => setTimeout(resolve, 5e3));
```

This adds a 5 second delay right before the selector is found.

**Comment by Jamie-BureauBeatrice** [comment]
> Hi @MrJamieMcC , I encountered this issue a few days ago myself.
> 
> The problem is that the page is being rendered too slow and the selector is being searched for too early, what you can do (temporarily) while we wait for @joaosilvalopes to respond is to add a delay before the selector.
> 
> fetchJobLinksUser.ts:13
> 
> ```js
> await new Promise((resolve) => setTimeout(resolve, 5e3));
> ```
> 
> This adds a 5 second delay right before the selector is found.

Thank you very much for this quick fix

**Comment by MrJamieMcC** [comment]
> Hi @MrJamieMcC , I encountered this issue a few days ago myself.
> 
> The problem is that the page is being rendered too slow and the selector is being searched for too early, what you can do (temporarily) while we wait for @joaosilvalopes to respond is to add a delay before the selector.
> 
> fetchJobLinksUser.ts:13
> 
> ```js
> await new Promise((resolve) => setTimeout(resolve, 5e3));
> ```
> 
> This adds a 5 second delay right before the selector is found.

Thank you for this quick fix <3

**Comment by IggsGrey** [comment]
@naihloan check in /fetch/fetchJobLinksUser.ts.
place the line of code before what is currently on line 13

**Comment by naihloan** [comment]
@IggsGrey thanks for the quick reply!

I did that modification as suggested, and the result was always the same: no element found for selector. I even applied the change in different lines, from 12 to 20, one check per time.

Is there another way in which I can provide more information to reproduce the issue and perhaps be able to solve it? Is the original code working for others as is? What may I be doing wrong?

**Comment by naihloan** [comment]
```
~/Public/linkedin-easy-apply-bot$ npm run start

> scripts@1.0.0 start
> ts-node ./scripts/apply.ts

> Logged in to LinkedIn
press enter to pause the program
Error: No element found for selector: input[id*="jobs-search-box-keyword-id"]
    at assert (/home/nilon/Public/linkedin-easy-apply-bot/node_modules/puppeteer-core/src/util/assert.ts:29:11)
    at IsolatedWorld.type (/home/nilon/Public/linkedin-easy-apply-bot/node_modules/puppeteer-core/src/common/IsolatedWorld.ts:348:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getJobSearchMetadata (/home/nilon/Public/linkedin-easy-apply-bot/fetch/fetchJobLinksUser.ts:14:3)
    at async fetchJobLinksUser (/home/nilon/Public/linkedin-easy-apply-bot/fetch/fetchJobLinksUser.ts:51:39)
    at async /home/nilon/Public/linkedin-easy-apply-bot/scripts/apply.ts:69:45

```

**Comment by naihloan** [comment]
I'm now under the suspicion that this could never run as long as I have 2FA enabled.

Just now, when I ran the code, I received an alert in my email that I needed to allow access. I was already signed in and enabled access again, and all the same, I wasn't able to complete the flow with `npm run start`. Can anyone run the code with 2FA, or am I missing the target?

**Comment by IggsGrey** [comment]
That's weird. The only time I run into issues with 2fa is when I try to run it in headless mode. Do you get a chrome window popup when you `npm run start`? If not then try `npm run apply`

**Comment by naihloan** [comment]
I see the window popup, but it's chromium

**Comment by IggsGrey** [comment]
for anyone else in the future who encounters this issue, here's [a fork](https://github.com/IggsGrey/linkedin-easy-apply-bot) I'm maintaining
