### ISSUE TITLE
Error: No element found for selector: #session_key

### ISSUE THREAD

**Issue by kashashyan** [joaosilvalopes/linkedin-easy-apply-bot#73]
I got this error : 
  at assert (C:\Users\hecha\OneDrive\Documents\GitHub\linkedin-easy-apply-bot\node_modules\puppeteer-core\src\util\assert.ts:29:11)
    at IsolatedWorld.type (C:\Users\hecha\OneDrive\Documents\GitHub\linkedin-easy-apply-bot\node_modules\puppeteer-core\src\common\IsolatedWorld.ts:348:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async login (C:\Users\hecha\OneDrive\Documents\GitHub\linkedin-easy-apply-bot\login\index.ts:17:3)
    at async C:\Users\hecha\OneDrive\Documents\GitHub\linkedin-easy-apply-bot\scripts\apply.ts:45:3

**Comment by kashashyan** [comment]
https://github.com/joaosilvalopes/linkedin-easy-apply-bot/assets/138378025/d272af31-1d41-46a0-9fb5-1e9961f12894

**Comment by MayankPant** [comment]
Any solutions for this problem?
