### ISSUE TITLE
Session error

### ISSUE THREAD

**Issue by babaz8** [joaosilvalopes/linkedin-easy-apply-bot#74]
HI,
I receive this error running the script

TimeoutError: Navigation timeout of 30000 ms exceeded
    at LifecycleWatcher._LifecycleWatcher_createTimeoutPromise (/Users/.../linkedin-easy-apply-bot/node_modules/puppeteer-core/src/common/LifecycleWatcher.ts:258:12)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at processTimers (node:internal/timers:514:7)
    at async Frame.goto (/Users/.../linkedin-easy-apply-bot/node_modules/puppeteer-core/src/common/Frame.ts:320:17)
    at async CDPPage.goto (/Users/.../linkedin-easy-apply-bot/node_modules/puppeteer-core/src/common/Page.ts:910:12)
    at async login (/Users/.../linkedin-easy-apply-bot/login/index.ts:14:3)
    at async /Users/.../linkedin-easy-apply-bot/scripts/apply.ts:45:3

**Comment by babaz8** [comment]
Error with the FW was blocking request
