### ISSUE TITLE
Easy APPLY ERROR

### ISSUE THREAD

**Issue by Kidus-berhanu** [joaosilvalopes/linkedin-easy-apply-bot#79]
logging in and searching is working fine but the bot is not applying 

PS C:\Users\Downloads\linkedin-easy-apply-bot-main> cd C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main
PS C:\Users\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main> npm run apply

> scripts@1.0.0 apply
> ts-node ./scripts/apply.ts SUBMIT

Logged in to LinkedIn
press enter to pause the program
TimeoutError: Waiting for selector `.jobs-search-results-list li.jobs-search-results__list-item:nth-child(7)` failed: Waiting failed: 5000ms exceeded
    at Timeout.<anonymous> (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\common\WaitTask.ts:79:11)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7)
PS C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main> npm run apply

> scripts@1.0.0 apply
> ts-node ./scripts/apply.ts SUBMIT

Logged in to LinkedIn
press enter to pause the program
Error applying to Python Developer at Unknown
Error applying to Python Automation Engineer - Plano TX or Mclean VA at Unknown
TimeoutError: Waiting failed: 30000ms exceeded
    at Timeout.<anonymous> (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\common\WaitTask.ts:79:11)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7)
Error applying to Python + SQL Developer at Unknown
Easy apply button not found in posting: https://www.linkedin.com/jobs/view/3792989682/?eBP=CwEAAAGM4xkL5RI-D-pROCPIrvUJhvaQAmBIfuu74JmWe32mC_5WnUlJ29ZH9xbXuudCUGDW0XGBRtVzK_t3AUTTi0DLDdV4v2sGYuRP0r2ImoqX9ABj-vPM8a401wTA-2Y9FgELXyO0MZiAKjFmEGx_WsPynXM7vtJ2NdL_7Lp0uF5Olroq9UbgOU66SW7MU2rW3DIkJBabGAczZyE4NwU4YfzmyPdIRci5ygSW_GZcMD2pn_U1bQ1PpwDGmd4UNceP075vJEameL61WqxA5uceM3SJ7rLdOOsCljEn0LJX7cu88vZqaCeSQA07EUfbC0AgX_vwzcA4-Q6LUmE5P5GuaHKXI5Bsswphc8IHTfWyfFNZKaf4LyYk34pAquFMPW0dYtPJjHwb6vwEOcFzDbwxVBhdSR7S&refId=5E4uCb3%2BW1nOCzi3oWpLOA%3D%3D&trackingId=KP3tSaGMtv7IdbsYBCgJYA%3D%3D&trk=flagship3_search_srp_jobs
Applied to Python Developer at Unknown
TimeoutError: Waiting failed: 30000ms exceeded
    at Timeout.<anonymous> (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\common\WaitTask.ts:79:11)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7)
TimeoutError: Waiting failed: 30000ms exceeded
    at Timeout.<anonymous> (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\common\WaitTask.ts:79:11)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7)
Error applying to Python Fullstack Developer - Trading Desk at Unknown
Error applying to Senior C++/Python Engineer at Unknown
Error applying to Python Data Engineer at Unknown
Error applying to Machine Learning Engineer at Unknown
Easy apply button not found in posting: https://www.linkedin.com/jobs/view/3794048521/?eBP=CwEAAAGM4xsEIs65XtqogYZuZH2PFJvAT2dziGcjUCSfftzV8IkOt2jhNDrF_l4G67l4k7Y2Uyvwly9-LC5ya3oiMRw7MZVa0km1Dof6P6YQfY1dPEst3L18NIPtETLw3OIuc9_hrwLdhJsbUYvwD3umaZD5Qfkh74O1WmDf5WstXyE70mVckEql8OhmAmUuUqmrf_9m4WBYePyyLJ_1Ze8D0K8gEdReYSxzW_KNoknMTuWlWkcNejdd0WVSkTMnINh5l5YUmTtEgC1TXuGrnZUKn_x0URA_dib0LE8iqxApUlk-5vX_D3ejsTpi6sRJPJdLaGaMrSzPCITxye5bFwGcoqxlujd88eEocr6V22cbdVMIDhyAntVgBuDpcr5TTICj-fdkgPhEDyjCmkz6uhsyoa56qBo4gsQ&refId=7ZjZlFulc0nIn%2Fihu3AT2A%3D%3D&trackingId=KbZYOiNJYHx5it1endBBHw%3D%3D&trk=flagship3_search_srp_jobs
Applied to Python Data Engineer at Unknown
Error applying to Python Developer - Data Engineer at Unknown
Error applying to Python Software Engineer (Backend) at Unknown
Error applying to Machine Learning Engineer at Unknown
Error applying to Python Developer at Unknown
Error applying to Senior Full Python Engineer at Unknown
Error applying to Lead Python Developer at Unknown

**Comment by christenbc** [comment]
https://github.com/joaosilvalopes/linkedin-easy-apply-bot/pull/81

**Comment by Kidus-berhanu** [comment]
@christenbc Thank you for #81
i am still getting this error 
i increased the timeouts and i have a very fast connection, but i am unable to solve this error
 
Logged in to LinkedIn
press enter to pause the program
Error applying to Senior Backend Engineer at Unknown
Applied to Machine Learning Engineer at Unknown
Error: Error: failed to find element matching selector "label[for="text-entity-list-form-component-formElement-urn-li-jobs-applyformcommon-easyApplyFormElement-3818428615-4581778243755756028-multipleChoice"]"
    at CdpElementHandle.$eval (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\api\ElementHandle.ts:410:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CdpFrame.$eval (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\api\Frame.ts:585:12)
    at async CdpPage.$eval (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\api\Page.ts:1159:12)
    at async fillMultipleChoiceFields (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\apply-form\fillMultipleChoiceFields.ts:13:19)
    at async fillFields (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\apply-form\fillFields.ts:41:3)
    at async apply (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\apply\index.ts:48:5)
    at async C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\scripts\apply.ts:89:7
Error applying to Senior Frontend Engineer at Unknown
Applied to DevOps Engineer (Artifactory & Xray) (Remote) at Unknown
Applied to Principal Fullstack Developer at Unknown
Applied to Senior Machine Learning Engineer – Knowledge Graph/Time- Series at Unknown
Error applying to Senior Backend Engineer at Unknown
Applied to Senior Machine Learning Engineer at Unknown
Error applying to Senior Backend Engineer at Unknown
Error applying to Senior Frontend Engineer at Unknown
Error applying to Software Engineer Specialist - PeopleSoft HCM and Payroll at Unknown
Error applying to Senior Python & Machine Learning Operations Engineer at Unknown
TimeoutError: Waiting failed: 30000ms exceeded
    at new WaitTask (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\common\WaitTask.ts:82:28)
    at IsolatedWorld.waitForFunction (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\api\Realm.ts:74:22)
    at CdpFrame.waitForFunction (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\api\Frame.ts:768:36)
    at CdpFrame.<anonymous> (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\util\decorators.ts:61:21)
    at CdpPage.waitForFunction (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\api\Page.ts:2960:29)
    at fetchJobLinksUser (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\fetch\fetchJobLinksUser.ts:90:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\scripts\apply.ts:69:45
TimeoutError: Waiting failed: 30000ms exceeded
    at new WaitTask (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\common\WaitTask.ts:82:28)
    at IsolatedWorld.waitForFunction (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\api\Realm.ts:74:22)
    at CdpFrame.waitForFunction (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\api\Frame.ts:768:36)
    at CdpFrame.<anonymous> (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\util\decorators.ts:61:21)
    at CdpPage.waitForFunction (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\api\Page.ts:2960:29)
    at fetchJobLinksUser (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\fetch\fetchJobLinksUser.ts:90:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\scripts\apply.ts:69:45
TimeoutError: Waiting failed: 30000ms exceeded
    at new WaitTask (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\common\WaitTask.ts:82:28)
    at IsolatedWorld.waitForFunction (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\api\Realm.ts:74:22)
    at CdpFrame.waitForFunction (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\api\Frame.ts:768:36)
    at CdpFrame.<anonymous> (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\util\decorators.ts:61:21)
    at CdpPage.waitForFunction (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\api\Page.ts:2960:29)
    at fetchJobLinksUser (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\fetch\fetchJobLinksUser.ts:90:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\scripts\apply.ts:69:45
TimeoutError: Waiting failed: 30000ms exceeded
    at new WaitTask (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\common\WaitTask.ts:82:28)
    at IsolatedWorld.waitForFunction (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\api\Realm.ts:74:22)
    at CdpFrame.waitForFunction (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\api\Frame.ts:768:36)
    at CdpFrame.<anonymous> (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\util\decorators.ts:61:21)
    at CdpPage.waitForFunction (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\api\Page.ts:2960:29)
    at fetchJobLinksUser (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\fetch\fetchJobLinksUser.ts:90:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\scripts\apply.ts:69:45
TimeoutError: Waiting failed: 30000ms exceeded
    at new WaitTask (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\common\WaitTask.ts:82:28)
    at IsolatedWorld.waitForFunction (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\api\Realm.ts:74:22)
    at CdpFrame.waitForFunction (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\api\Frame.ts:768:36)
    at CdpFrame.<anonymous> (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\util\decorators.ts:61:21)
    at CdpPage.waitForFunction (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\api\Page.ts:2960:29)
    at fetchJobLinksUser (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\fetch\fetchJobLinksUser.ts:90:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\scripts\apply.ts:69:45
Error applying to Senior Applied Machine Learning Engineer - Merchant New Products and Experience at Unknown
TimeoutError: Waiting failed: 30000ms exceeded
    at new WaitTask (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\common\WaitTask.ts:82:28)
    at IsolatedWorld.waitForFunction (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\api\Realm.ts:74:22)
    at CdpFrame.waitForFunction (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\api\Frame.ts:768:36)
    at CdpFrame.<anonymous> (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\util\decorators.ts:61:21)
    at CdpPage.waitForFunction (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\api\Page.ts:2960:29)
    at fetchJobLinksUser (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\fetch\fetchJobLinksUser.ts:90:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\scripts\apply.ts:69:45

**Comment by Kidus-berhanu** [comment]
press enter to pause the program
SyntaxError: Invalid regular expression: /c++/i: Nothing to repeat
    at new RegExp (<anonymous>)
    at fillTextFields (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\apply-form\fillTextFields.ts:22:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fillFields (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\apply-form\fillFields.ts:28:3)
    at async apply (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\apply\index.ts:46:5)
    at async C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\scripts\apply.ts:95:7
SyntaxError: Invalid regular expression: /c++/i: Nothing to repeat
    at new RegExp (<anonymous>)
    at fillTextFields (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\apply-form\fillTextFields.ts:22:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fillFields (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\apply-form\fillFields.ts:28:3)
    at async apply (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\apply\index.ts:46:5)
    at async C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\scripts\apply.ts:95:7
Applied to Machine Learning Engineer at Unknown
SyntaxError: Invalid regular expression: /c++/i: Nothing to repeat
    at new RegExp (<anonymous>)
    at fillTextFields (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\apply-form\fillTextFields.ts:22:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fillFields (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\apply-form\fillFields.ts:28:3)
    at async apply (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\apply\index.ts:46:5)
    at async C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\scripts\apply.ts:95:7
SyntaxError: Invalid regular expression: /c++/i: Nothing to repeat
    at new RegExp (<anonymous>)
    at fillTextFields (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\apply-form\fillTextFields.ts:22:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fillFields (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\apply-form\fillFields.ts:28:3)
    at async apply (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\apply\index.ts:46:5)
    at async C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\scripts\apply.ts:95:7
SyntaxError: Invalid regular expression: /c++/i: Nothing to repeat
    at new RegExp (<anonymous>)
    at fillTextFields (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\apply-form\fillTextFields.ts:22:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fillFields (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\apply-form\fillFields.ts:28:3)
    at async apply (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\apply\index.ts:46:5)
    at async C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\scripts\apply.ts:95:7
SyntaxError: Invalid regular expression: /c++/i: Nothing to repeat
    at new RegExp (<anonymous>)
    at fillTextFields (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\apply-form\fillTextFields.ts:22:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fillFields (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\apply-form\fillFields.ts:28:3)
    at async apply (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\apply\index.ts:46:5)
    at async C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\scripts\apply.ts:95:7
SyntaxError: Invalid regular expression: /c++/i: Nothing to repeat
    at new RegExp (<anonymous>)
    at fillTextFields (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\apply-form\fillTextFields.ts:22:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fillFields (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\apply-form\fillFields.ts:28:3)
    at async apply (C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\apply\index.ts:46:5)
    at async C:\Users\kidus\Downloads\linkedin-easy-apply-bot-main\linkedin-easy-apply-bot-main\scripts\apply.ts:95:7
